export const CUSTOMERS = [
  { id: '1', name: 'Flossie Cubbon', email: 'fcubbon0@bizjournals.com' },
  { id: '2', name: 'Janetta Jouanet', email: 'jjouanet1@wired.com' },
  { id: '3', name: 'Saleem Pettengell', email: 'spettengell2@amazon.com' },
  { id: '4', name: 'Shandy Siddle', email: 'ssiddle3@arizona.edu' },
  { id: '5', name: 'Neil Castanie', email: 'ncastanie4@cpanel.net' },
  { id: '6', name: 'Laney Wortley', email: 'lwortley5@opera.com' },
  { id: '7', name: 'Allyn McSaul', email: 'amcsaul6@redcross.org' },
  { id: '8', name: 'Freda Snadden', email: 'fsnadden7@hugedomains.com' },
  { id: '9', name: 'Hillard Baum', email: 'hbaum8@list-manage.com' },
  { id: '10', name: 'Isa Lieber', email: 'ilieber9@storify.com' },
  { id: '11', name: 'Margret Hayden', email: 'mhaydena@cnet.com' },
  { id: '12', name: 'Carleen Treadgold', email: 'ctreadgoldb@un.org' },
  { id: '13', name: 'Milicent Sammars', email: 'msammarsc@uiuc.edu' },
  { id: '14', name: 'Cherlyn Lownds', email: 'clowndsd@amazonaws.com' },
  { id: '15', name: 'Quintina Slessor', email: 'qslessore@youku.com' },
  { id: '16', name: 'Sky Pratte', email: 'sprattef@rakuten.co.jp' },
  { id: '17', name: 'Dede De Moreno', email: 'ddeg@ow.ly' },
  { id: '18', name: 'Vivianna Lardnar', email: 'vlardnarh@nsw.gov.au' },
  { id: '19', name: 'Alva Dawidowitz', email: 'adawidowitzi@fastcompany.com' },
  { id: '20', name: 'Audrye De Roberto', email: 'adej@issuu.com' },
  { id: '21', name: 'Rori Wrench', email: 'rwrenchk@yellowpages.com' },
  { id: '22', name: 'Karl Kingett', email: 'kkingettl@pinterest.com' },
  { id: '23', name: 'Clemmy Ludron', email: 'cludronm@google.es' },
  { id: '24', name: 'Phil Fawckner', email: 'pfawcknern@jugem.jp' },
  { id: '25', name: 'Desmond Alabone', email: 'dalaboneo@home.pl' },
  { id: '26', name: 'Lila Sopper', email: 'lsopperp@imageshack.us' },
  { id: '27', name: 'Clo Pinches', email: 'cpinchesq@eventbrite.com' },
  { id: '28', name: 'Tedi Warsap', email: 'twarsapr@foxnews.com' },
  { id: '29', name: 'Marshal Burnie', email: 'mburnies@jiathis.com' },
  { id: '30', name: 'Morganica Gather', email: 'mgathert@themeforest.net' },
];
